version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
          docker login -u $DOCKER_ID -p $DOCKER_PASS
      # build the application image
      - run: docker build --build-arg REACT_APP_API_URL=$REACT_APP_API_URL --build-arg REACT_APP_STRIPE_KEY=$REACT_APP_STRIPE_KEY --rm -f Dockerfile -t $DOCKER_ID/csgoed-frontend .

      # deploy the image
      - run: docker push $DOCKER_ID/csgoed-frontend
