name: deploy-auth-service

env:
  KUBECONFIG: /home/deploy/config
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build --build-arg REACT_APP_AUTH_SERVICE_URL=${{ REACT_APP_AUTH_SERVICE_URL }} --build-arg REACT_APP_USER_SERVICE_URL=${{ REACT_APP_USER_SERVICE_URL }} --build-arg REACT_APP_STRIPE_KEY=${{ REACT_APP_STRIPE_KEY }} -f Dockerfile  -t kamilwronka7/csgoed-frontend .
      - run: docker login -u $DOCKER_ID -p $DOCKER_PASS
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      - run: docker push kamilwronka7/csgoed-frontend
      - run: sudo mkdir -p /home/deploy
      - run: echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $KUBECONFIG
      - run: kubectl rollout restart deployment csgoed-frontend-depl
